# Generated by Django 3.1.3 on 2024-04-04 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('posted_time', models.TimeField(auto_now_add=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('is_assignment', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(default=datetime.time(23, 59))),
                ('total_marks', models.IntegerField(default=100)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
            ],
        ),
    ]
