# Generated by Django 3.1.3 on 2024-04-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='matirial',
            field=models.FileField(default=True, max_length=256, null=True, upload_to='posts/'),
        ),
    ]
