# Generated by Django 3.1.3 on 2024-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_matirial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='matirial',
            field=models.FileField(default=False, max_length=256, null=True, upload_to='posts/'),
        ),
    ]
