# Generated by Django 3.1.3 on 2024-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240404_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='matirial',
            field=models.FileField(blank=True, default=False, max_length=256, null=True, upload_to='posts/'),
        ),
    ]
